dist: bionic
language: cpp
before_install:
  - sudo apt-get install -y cppcheck libbluetooth3 libbluetooth-dev libsqlite3-0 libsqlite3-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - make test
