dist: xenial
language: cpp
install:
  - sudo apt -y install libbluetooth3 libbluetooth-dev libsqlite3-0 libsqlite3-dev cppcheck
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - make test
